/**
 * utils/qrParser.ts
 * Structured parsing for QR codes scanned on the Scan-to-Donate screen.
 *
 * Recognised payloads, in match order:
 *   1. IndigoPay deep link      stellar-indigopay://donate?projectId=X&amount=Y&memo=Z
 *   2. Legacy deep link         indigopay://donate?wallet=G...&project=X&amount=Y
 *   3. SEP-0007 payment URI     web+stellar:pay?destination=G...&amount=Y&memo=Z
 *      (this is what the web app's WalletAddressQRCode component encodes)
 *   4. Raw Stellar address      G... (56 chars)
 *   5. URL containing a Stellar address anywhere in it
 *
 * Anything else parses as { type: "unknown" } so the scan screen can show
 * an explicit "not a valid IndigoPay QR" error instead of failing silently.
 *
 * #906: the regexes and format validators below are re-exported from
 * `lib/linkRouter.ts` — the single place inbound-link rules live — rather
 * than duplicated here, so this parser can never drift from the rules
 * every other inbound surface (deep links, notifications, clipboard) is
 * held to. See lib/__tests__/linkRouterConvergence.test.ts.
 */
import { isValidStellarAddress } from "./stellarValidation";
import {
  DEEP_LINK_RE,
  LEGACY_DEEP_LINK_RE,
  SEP0007_PAY_RE,
  RAW_ADDRESS_RE,
  EMBEDDED_ADDRESS_RE,
  MAX_INPUT_LENGTH,
  isValidEntityId,
  hasDuplicateParam,
  sanitizeAmountParam,
  sanitizeMemoParam,
} from "../lib/linkRouter";

export interface ParsedQR {
  type: "donate_link" | "stellar_address" | "unknown";
  projectId?: string;
  address?: string;
  amount?: string;
  memo?: string;
  raw: string;
}

export function parseQRData(data: string): ParsedQR {
  const raw = typeof data === "string" ? data : String(data ?? "");
  const input = raw.trim();

  // DoS / truncation guard — never run a regex against a pathological
  // amount of scanned text.
  if (!input || input.length > MAX_INPUT_LENGTH) {
    return { type: "unknown", raw };
  }

  // Pattern 1: IndigoPay deep link with an embedded projectId.
  const deepLinkMatch = input.match(DEEP_LINK_RE);
  if (deepLinkMatch) {
    const params = new URLSearchParams(deepLinkMatch[1]);
    if (
      hasDuplicateParam(params, "projectId") ||
      hasDuplicateParam(params, "address") ||
      hasDuplicateParam(params, "amount") ||
      hasDuplicateParam(params, "memo")
    ) {
      return { type: "unknown", raw };
    }

    const projectIdRaw = params.get("projectId")?.trim();
    const projectId =
      projectIdRaw && isValidEntityId(projectIdRaw) ? projectIdRaw : undefined;
    const address = params.get("address")?.trim();
    const validAddress = isValidStellarAddress(address) ? address : undefined;

    if (!projectId && !validAddress) {
      return { type: "unknown", raw };
    }
    return {
      type: "donate_link",
      projectId,
      address: validAddress,
      amount: sanitizeAmountParam(params.get("amount")),
      memo: sanitizeMemoParam(params.get("memo")),
      raw,
    };
  }

  // Pattern 2: legacy deep link (pre-#84 QR codes already in the wild).
  const legacyMatch = input.match(LEGACY_DEEP_LINK_RE);
  if (legacyMatch) {
    const params = new URLSearchParams(legacyMatch[1]);
    if (
      hasDuplicateParam(params, "wallet") ||
      hasDuplicateParam(params, "project") ||
      hasDuplicateParam(params, "amount") ||
      hasDuplicateParam(params, "memo")
    ) {
      return { type: "unknown", raw };
    }

    const wallet = params.get("wallet")?.trim() ?? "";
    if (!isValidStellarAddress(wallet)) {
      return { type: "unknown", raw };
    }
    const projectIdRaw = params.get("project")?.trim();
    const projectId =
      projectIdRaw && isValidEntityId(projectIdRaw) ? projectIdRaw : undefined;

    return {
      type: "donate_link",
      projectId,
      address: wallet,
      amount: sanitizeAmountParam(params.get("amount")),
      memo: sanitizeMemoParam(params.get("memo")),
      raw,
    };
  }

  // Pattern 3: SEP-0007 pay URI, as generated by WalletAddressQRCode on web.
  const sepMatch = input.match(SEP0007_PAY_RE);
  if (sepMatch) {
    const params = new URLSearchParams(sepMatch[1]);
    if (
      hasDuplicateParam(params, "destination") ||
      hasDuplicateParam(params, "amount") ||
      hasDuplicateParam(params, "memo")
    ) {
      return { type: "unknown", raw };
    }

    const destination = params.get("destination")?.trim() ?? "";
    if (!isValidStellarAddress(destination)) {
      return { type: "unknown", raw };
    }
    return {
      type: "stellar_address",
      address: destination,
      amount: sanitizeAmountParam(params.get("amount")),
      memo: sanitizeMemoParam(params.get("memo")),
      raw,
    };
  }

  // Pattern 4: bare Stellar public key.
  const addressMatch = input.match(RAW_ADDRESS_RE);
  if (addressMatch) {
    return { type: "stellar_address", address: addressMatch[1], raw };
  }

  // Pattern 5: any other URL / text with a Stellar address embedded in it.
  const embeddedMatch = input.match(EMBEDDED_ADDRESS_RE);
  if (embeddedMatch) {
    return { type: "stellar_address", address: embeddedMatch[1], raw };
  }

  return { type: "unknown", raw };
}
