apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: canary-vs-stable
  namespace: stellar-indigopay
spec:
  args:
    - name: canary-hash
    - name: stable-hash
  metrics:
    - name: error-rate-comparison
      interval: 1m
      count: 10
      successCondition: result == 1
      provider:
        prometheus:
          address: http://prometheus-operated.monitoring.svc:9090
          query: |
            scalar(
              sum(backend:canary:error_rate_10m{pod_template_hash="{{args.canary-hash}}"} or backend:canary:error_rate_10m{rollouts_pod_template_hash="{{args.canary-hash}}"})
              <= bool
              (sum(backend:canary:error_rate_10m{pod_template_hash="{{args.stable-hash}}"} or backend:canary:error_rate_10m{rollouts_pod_template_hash="{{args.stable-hash}}"} or vector(0)) * 1.5)
            )

    - name: p95-latency-comparison
      interval: 1m
      count: 10
      successCondition: result == 1
      provider:
        prometheus:
          address: http://prometheus-operated.monitoring.svc:9090
          query: |
            scalar(
              sum(backend:canary:p95_latency_10m{pod_template_hash="{{args.canary-hash}}"} or backend:canary:p95_latency_10m{rollouts_pod_template_hash="{{args.canary-hash}}"})
              <= bool
              (sum(backend:canary:p95_latency_10m{pod_template_hash="{{args.stable-hash}}"} or backend:canary:p95_latency_10m{rollouts_pod_template_hash="{{args.stable-hash}}"} or vector(0)) * 1.2)
            )
